### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AlexZd** [Yalantis/PullToRefresh#10]
I'm using `swift2.0` branch.
Steps to reproduce:
1. Download demo project.
2. Insert `UIViewController` between `UINavigationController` and sample `ViewController`
3. Add button on new `UIViewController` and link it to sample `ViewController`, so now you can tap on button and push sample `ViewController`.
4. Inside ViewController.swift add `deinit` method. You can add printing or use breakpoints.
5. Run application and go to sample screen.
6. Go back, sample should be deallocated, but no. You can comment `addPullToRefresh` method in `viewDidAppear` and repeat test and you will get deallocation.

**Comment by AlexZd** [comment]
Also in my application I'm getting crash because of this leak like:

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7facd1866200 of class UICollectionView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7facd147c960> (
<NSKeyValueObservance 0x7facd147cc70: Observer: 0x7facd147bd70, Key path: contentOffset, Options: <New: NO, Old: NO, Prior: NO> Context: 0x7facd147bdf8, Property: 0x7facd147c910>
```

**Comment by Art3mS1d** [comment]
Thanks you, @AlexZd . I fixed it. https://github.com/Yalantis/PullToRefresh/commit/c2958eb91b0efd9f625897025987f3362c546c5f
. Soon will be in master
