### ISSUE TITLE
Install 3.1.0 failed with CocoaPods

### ISSUE THREAD

**Issue by zizicici** [Yalantis/PullToRefresh#105]
# Report

I can't install PullToRefresh 3.1.0, maybe you miss set the tag and push new version to CocoaPods?

###  What did you do?

Write 'pod 'PullToRefresher', '~> 3.1' in my podfile and try to update my project

### What did you expect to happen?

Success.  

### What happened instead?

> [!] CocoaPods could not find compatible versions for pod "PullToRefresher":
>   In Podfile:
>     PullToRefresher (~> 3.1)
> 
> None of your spec sources contain a spec satisfying the dependency: `PullToRefresher (~> 3.1)`.
> 
> You have either:
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

### Your Environment

- Xcode version: Xcode 10
- If you use Cocoapods: 1.5.3

**Comment by rnkyr** [comment]
hi, @beimen!
yep, we've not updated cocoapods remote servers yet
will be available soon

**Comment by rnkyr** [comment]
meanwhile you can fetch it directly by specifying branch

**Comment by rnkyr** [comment]
hey, @beimen!
sorry for the delay. v3.1 is deployed, check out
