### ISSUE TITLE
The opposite refresher is missing

### ISSUE THREAD

**Issue by zizicici** [Yalantis/PullToRefresh#107]
# Report

> It can be reproduced in PullToRefreshDemo.xcodeproj

###  What did you do?

> Pull down the table view, and don't fire the action of the top refresher, and hold the finger.
> Scroll up the table view rapidly.
> Go to the bottom of the table view.

### What did you expect to happen?

> The bottom refresher is existing.  

### What happened instead?

> The bottom refresher is missing.

### Your Environment

- Version of the component: 3.1.0
- Swift version: 4.2
- iOS version: iOS 12.0.1
- Device: iPhone X
- Xcode version: 10.0 (10A255)
- CocoaPods: 1.5.3

### Project that demonstrates the bug

> The PullToRefreshDemo.xcodeproj can reproduce it.

### Advice

In the `override open func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?)` of `PullToRefresher.swift`, I change some code in the first `if` part:

In the offset switch, maybe PullToRefresh need handle the `offset > 0` case:

`                if state != .loading && state != .finished && state != .initial {
                    state = .initial
                }`

Maybe it is a workaround.

**Comment by zizicici** [comment]
I just fork the repo and commit the change. It may resolve it.

**Comment by sergey-prikhodko** [comment]
Released in the new version - [3.3](https://github.com/Yalantis/PullToRefresh/tree/3.3)
