### ISSUE TITLE
Problem in scrolling , when increas cell height 540

### ISSUE THREAD

**Issue by ShardaPrasad** [Yalantis/PullToRefresh#108]
Hi,
Its good library for pull to refresh but i am facing problem, when i increase cell size 540. That condition .bottom scroll automatic scroll approx. 10 or 11 index.

**Comment by sergey-prikhodko** [comment]
Hi @ShardaPrasad , sorry for the late reply.
I tested this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue
