### ISSUE TITLE
Getting Crash 

### ISSUE THREAD

**Issue by sourov2008** [Yalantis/PullToRefresh#115]
# Report

> Please add images. 

<img width="1296" alt="Screen Shot 2019-11-23 at 12 22 04 PM" src="https://user-images.githubusercontent.com/4990835/69474619-8e0f5080-0ded-11ea-808b-281f6d335adf.png">

## Report a bug
> Please describe what you want to add to the component. 
Getting crash.

Step 1 - Working fine pull to refresh
Step 2 - popup
Step 3 - tap Humberger menu and getting Crash

on
    deinit {
        tableView.removeAllPullToRefresh()
    }
I deceleader on ViewDidLoad

**Comment by rnkyr** [comment]
hey, @sourov2008!

looks like your `tableView` being deinitialized before the controller itself
it has nothing to do with the lib, so I suggest you try to figure out why table deinitializes
