### ISSUE TITLE
version 3.3 freeze the app and high cpu usage 100%

### ISSUE THREAD

**Issue by mouness2020** [Yalantis/PullToRefresh#119]
version 3.3 freeze the app and high cpu usage 100%

**Comment by sergey-prikhodko** [comment]
Hello @mouness2020, could you provide me more information about steps to reproduce and iOS version?
And could you remake this issue using our template for issues, if it possible, thank you 🙏

**Comment by sergey-prikhodko** [comment]
cant reproduce
