### ISSUE TITLE
'endRefreshing' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by rami965** [Yalantis/PullToRefresh#122]
I got this error when I tried to call endRefreshing()
![Screen Shot 2020-06-06 at 9 56 23 PM](https://user-images.githubusercontent.com/20938033/83953450-d1d51f00-a840-11ea-9389-af7c9c4f2205.png)

Please consider changing the function to be `open` instead of `internal`

Thank you

**Comment by sergey-prikhodko** [comment]
Hello, you can call `endRefreshing(at: _position)` on scroll view.
If you have some extra questions, let me know
