### ISSUE TITLE
Dynamic height for RefreshView

### ISSUE THREAD

**Issue by StuartMorris0** [Yalantis/PullToRefresh#19]
Hello,

Is there a way to create a dynamic height for the refresh view. The reason I ask is that we are looking to implement the pull to refresh functionality from here.

We have a background colour set for the table view already. The pull to refresh view background colour is different. When you drag over the height of the refresh view you see the background colour of the table view. 

I was hoping it would work like the default pull to refresh where the background colour is pulled along with it. Thanks

**Comment by KaterynaZaikina** [comment]
@StuartMorris0 you can look at this solution https://github.com/Yalantis/PullToRefresh/pull/24

**Comment by StuartMorris0** [comment]
Hey @serejahh. I am not sure the expected behaviour from this, but the issue still exists for us. 

What happens is the refresh view that we create is added behind the tableView and the height of that refresh view is not dynamic when scrolled past its original height. 

Here is an example image from looking at the view layout.
![screen shot 2016-08-09 at 16 29 21](https://cloud.githubusercontent.com/assets/1994135/17522365/aabb4b00-5e4e-11e6-96c6-97c4e81b110c.png)

Here is a video example:
http://quick.as/1Ov9HBr86

In our case we need the background colour of the tableview which can be seen at the top once scrolled past the height of the Refresh view. But we would expect the refresh view to dynamically change its height once past its original. 

Could this be re-opened? Thanks
