### ISSUE TITLE
Fatal Exception: NSRangeException Cannot remove an observer <DigitalPour.PullToRefresh 0x132217b40> for the key path "contentOffset" from <UITableView 0x12d8dcc00> because it is not registered as an observer.

### ISSUE THREAD

**Issue by brewmium** [Yalantis/PullToRefresh#33]
Just received an odd crash in PullToRefesh. I wonder if a semaphore around addScrollViewObserving/removeScrollViewObserving the observer may be in order?

![screen shot 2016-06-23 at 3 53 51 pm](https://cloud.githubusercontent.com/assets/923549/16317986/0070a220-395b-11e6-845e-ab6ef578793b.png)

**Comment by ibakurov** [comment]
Even though it seemed to be fixed, I do receive this crash from time to time. Could not debug why and under which circumstances, but telling, just so you are aware that it is not fully resolved with deinit solution. Once I have more details I'll definitely share them here.
