### ISSUE TITLE
Dyanmic Height issue

### ISSUE THREAD

**Issue by StuartMorris0** [Yalantis/PullToRefresh#38]
Re-opening issue https://github.com/Yalantis/PullToRefresh/issues/19

From previous last comment:
Hey @serejahh. I am not sure the expected behaviour from this, but the issue still exists for us. 

What happens is the refresh view that we create is added behind the tableView and the height of that refresh view is not dynamic when scrolled past its original height. 

Here is an example image from looking at the view layout.
![screen shot 2016-08-09 at 16 29 21](https://cloud.githubusercontent.com/assets/1994135/17522365/aabb4b00-5e4e-11e6-96c6-97c4e81b110c.png)

Here is a video example:
http://quick.as/1Ov9HBr86

In our case we need the background colour of the tableview which can be seen at the top once scrolled past the height of the Refresh view. But we would expect the refresh view to dynamically change its height once past its original. 

Could this be re-opened? Thanks

**Comment by serejahh** [comment]
Have you already tried to setup constraints for the behaviour?

**Comment by StuartMorris0** [comment]
Hey, No!

I am not sure what constraint would be needed here. What was you thinking?

**Comment by serejahh** [comment]
I've played a bit with constraints. I guess, because it's a table view header it's not easy enough to setup this kind of constraints. The easiest way is to set the same background color

**Comment by StuartMorris0** [comment]
I'll try and have a look at this in more depth. Surely the background view for the tableView refresh can be set with a constraint and not set height(max height) at least that is my thoughts.
