### ISSUE TITLE
Swift 2.3 + Swift 3.0

### ISSUE THREAD

**Issue by pmusolino** [Yalantis/PullToRefresh#41]
Hi!

I suggest to introduce two branches that works with swift 2.3 and swift 3.0.

Thanks
-Paolo

**Comment by serejahh** [comment]
Hi @Codeido! Sure, it's almost done - https://github.com/Yalantis/PullToRefresh/pull/42

**Comment by ibakurov** [comment]
Any timelines when it is going to be merged in master and pushed to cocoapods?

**Comment by serejahh** [comment]
Sure, I'll merge it today 👍

**Comment by serejahh** [comment]
Now `master` contains swift 3, `swift2` contains the last 2.x version. Everything is available in cocoapods
