### ISSUE TITLE
Can I use it in Objective C project?

### ISSUE THREAD

**Issue by czars** [Yalantis/PullToRefresh#43]

**Comment by serejahh** [comment]
Hi @czars!

Unfortunately, we didn't have intention to support objective-c

**Comment by nderkach** [comment]
I've made a fork with Obj-C support here: https://github.com/BlipMe/PullToRefresh

Really all that was required was to implement a few additional initializers. I've also included obj-c examples creating a custom pull-to-refresh view.

**Comment by czars** [comment]
@nderkach  thanks for your contribution! I did solved my problem
