### ISSUE TITLE
Can I temporarily disable pull-to-refresh?

### ISSUE THREAD

**Issue by vietstone-ng** [Yalantis/PullToRefresh#53]
Hi,
I want to use pull-to-refresh. But sometimes, I want to disable it, then enable later.
Can I do it with this library?
Thank you.

**Comment by serejahh** [comment]
hi @vietstone. You can remove it and add again when it's needed, but I'll leave the issues as an improvement

**Comment by vietstone-ng** [comment]
oh, nice @serejahh . Thank you.

**Comment by sergey-prikhodko** [comment]
Released in the new version - [3.3](https://github.com/Yalantis/PullToRefresh/tree/3.3)
