### ISSUE TITLE
Fix insets for UITableViewController

### ISSUE THREAD

**Issue by nickdnk** [Yalantis/PullToRefresh#55]
Hey

When used in a storyboard UITableViewController, the refresher resets the insets to .zero, causing the scroll view to go under the navigation bar and tab bar (if you have one). It should do 64 for top and 49 for bottom insets to match, but there's no way to change this.

So for some reason it's setting scrollViewDefaultInsets incorrectly, not taking into account navigation bar or tab bar.

iOS 10, Xcode 8

## EDIT: I solved it by disabling "Adjust scroll view insets" and manually setting insets in `viewDidLoad()` - perhaps make this part of the documentation :)

**Comment by nderkach** [comment]
Had the same issue, adjusting tableview `contentInset`, did the job. `automaticallyAdjustsScrollViewInsets` was not required.

**Comment by jdziegler** [comment]
Experiencing the same issue when programmatically creating a UIViewController that has a table view.
