### ISSUE TITLE
NSInternalInconsistencyException bug

### ISSUE THREAD

**Issue by woodchuckkkk** [Yalantis/PullToRefresh#57]
###  What did you do?

Crash would definitely be caused if you release the viewController that contains tableview and topPullToRefresh, while you are running your demo with an ipad2 ios9. In this case, calling removePullToRefresh() in deinit() is invalid. There would be some unknown reasons that may cause the delay of releasing topPullToRefresh rather than tableview, and the topPullToRefresh still keep observing tableview.

> Crash Log:
> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7e2cf200 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7be86b20> (
<NSKeyValueObservance 0x7be844e0: Observer: 0x7d27d380, Key path: contentOffset, Options: <New: NO, Old: NO, Prior: NO> Context: 0x7d27d3ec, Property: 0x7bf74ff0>
<NSKeyValueObservance 0x7be854a0: Observer: 0x7d27d380, Key path: contentSize, Options: <New: NO, Old: NO, Prior: NO> Context: 0x7d27d3ec, Property: 0x7be854d0>
<NSKeyValueObservance 0x7be859b0: Observer: 0x7d27d380, Key path: contentInset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x7d27d3ec, Property: 0x7be859e0>
<NSKeyValueObservance 0x7be864b0: Observer: 0x7be862d0, Key path: contentOffset, Options: <New: NO, Old: NO, Prior: NO> Context: 0x7be8633c, Property: 0x7bf74ff0>
<NSKeyValueObservance 0x7be86510: Observer: 0x7be862d0, Key path: contentSize, Options: <New: NO, Old: NO, Prior: NO> Context: 0x7be8633c, Property: 0x7be854d0>
<NSKeyValueObservance 0x7be86ca0: Observer: 0x7be862d0, Key path: contentInset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x7be8633c, Property: 0x7be859e0>
)'

### Your Environment

- Swift version: Swift 3.0
- iOS version: iOS9
- Device: iPad2
- Xcode version: Version 8.2.1 (8C1002)

**Comment by mahmutpinarbasi** [comment]
Having the same issue on iOS 10.2 with iPhone 5 Simulator

**Comment by serejahh** [comment]
Guys, thanks for reporting the bug. We'll try to fix it

**Comment by murdly** [comment]
I was holding a reference to `refresher=PullToRefresh()` object. Calling `refresher=nil` while removing the refresher in `deinit` solved the problem.

**Comment by Vinzius** [comment]
Same problem. Fix from murdly works, but not really fun to have an optional var. Maybe I'm just going to remove the lib, too bad.

**Comment by TimothyChilvers** [comment]
+1 - abandoning this lib in favour of going iOS 10 only.

**Comment by srj0x0** [comment]
@Vinzius, @TimothyChilvers Hi guys, thank for the report. When you add an instance of PullToRefresh to a UIScrollView (or its subclass), it becomes retained. So, you have a strong reference to it from the scroll view. It seems that you have another strong reference inside the controller. Therefore, you need to use a weak reference in the controller or not use it and create refresher instance before adding.
