### ISSUE TITLE
Why not let the `removePullToRefresh` accept optional param?

### ISSUE THREAD

**Issue by PMExtra** [Yalantis/PullToRefresh#60]
```Swift
extension UITableView {
    public func remove(pullToRefresh: PullToRefresh?) {
        guard let refresh = pullToRefresh else {
            return
        }
        self.removePullToRefresh(refresh)
    }
}
```

I extend it for more convenient deinit.

**Comment by Vodolazkyi** [comment]
Hi! Thank you for question. For what purpose can this be useful ?

**Comment by PMExtra** [comment]
In controller deinitializer. By default, I have to check the refresher not be null and call the remove method. If let the remove accept null reference and check it internal, I could call it without a care.

On 07/11/2017 22:09, Vodolazkyi wrote: Hi! Thank you for question. For what purpose can this be useful ?
