### ISSUE TITLE
Layout is off on iPhoneX if using Xcode9 and WKWebView

### ISSUE THREAD

**Issue by ykeisuke** [Yalantis/PullToRefresh#78]
# Report
Hi
Indicator is not center (⚭-⚭  )
See following image. On this image, changed background color for debug.
![simulator screen shot - iphone x - 2017-10-06 at 18 58 21](https://user-images.githubusercontent.com/3081092/31273329-191c65b2-aac9-11e7-9f37-319bdf859c0d.png)

###  What did you do?

I'll description.

1. Installed Xcode9 GM(Version 9.0 (9A235))

2. Clone Yalantis/PullToRefresh.

3. Open cloned Demo project.

4. Changed `Swift Language Version` to `Swift 4.0` on the `PullToRefreshDemo` target.

5. Changed storyboard settings:

<img width="803" alt="_2017-10-06_19_13_50" src="https://user-images.githubusercontent.com/3081092/31273704-b5bd9a70-aaca-11e7-9662-439c8c07faa1.png">

6. I did set WKWebView for your DEMO project using following source-code: 
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        let wkwebview = WKWebView()
        wkwebview.navigationDelegate = self
        wkwebview.uiDelegate = self
        wkwebview.scrollView.delegate = self
        
        if #available(iOS 11.0, *) {
            wkwebview.insetsLayoutMarginsFromSafeArea = true
        }
        
        let refresher = PullToRefresh()
        wkwebview.scrollView.addPullToRefresh(refresher, action: {
            wkwebview.reloadFromOrigin()
        })
        
        let urlRequest = URLRequest(url: URL.init(string: "https://stackoverflow.com/search?q=Yalantis+PullToRefresh")!)
        
        wkwebview.load(urlRequest)
        self.view = wkwebview
```

And, I set the background color to orange color.

7. And delete Table view in swift file and storyboard file.

8. Layout is off when pulling view.

![simulator screen shot - iphone x - 2017-10-06 at 18 58 21](https://user-images.githubusercontent.com/3081092/31273329-191c65b2-aac9-11e7-9f37-319bdf859c0d.png)

### What did you expect to happen?

I need this:
![expected_simulator-screen-shot---iphone-x---2017-10-06-at-18_58_21](https://user-images.githubusercontent.com/3081092/31276634-e6620154-aad7-11e7-8cdd-26401fa15613.png)

Or this:
![expected2_simulator-screen-shot---iphone-x---2017-10-06-at-18_58_21](https://user-images.githubusercontent.com/3081092/31276637-ea944782-aad7-11e7-8875-8e886167b4e7.png)

I used the photoshop for make this images.

### What happened instead?

On left side, shown white space(layout is off) like following image: 

![simulator screen shot - iphone x - 2017-10-06 at 18 58 21](https://user-images.githubusercontent.com/3081092/31273329-191c65b2-aac9-11e7-9f37-319bdf859c0d.png)

### Your Environment

- Version of the component: develop branch.
- Swift version: 4.0
- iOS version: iOS11.0.0(Simulator)
- Device: iPhoneX
- Xcode version: Version 9.0 (9A235)
- If you use Cocoapods: I did not use Cocoapods.
- If you use Carthage: I did not use Carthage.

### Project that demonstrates the bug

You can download from my repository:
https://github.com/ykeisuke/PullToRefresh/tree/develop-mine

### MEMO:

My private project has same problem on the iPhoneX and iOS11.

Thank you!ƪ(•ᴗ•ƪ)

**Comment by srj0x0** [comment]
@ykeisuke you can implement custom PullToRefresh and use it as well.
