### ISSUE TITLE
Merge Swift 2.0 version

### ISSUE THREAD

**Issue by tapz** [Yalantis/PullToRefresh#9]
Time to merge the swift 2.0 version and make a new pod version? iOS9 and Xcode 7 GM have been out for couple of weeks now.

**Comment by jlalvarez18** [comment]
:+1:

**Comment by serejahh** [comment]
@maximletushov, do you need some help?

**Comment by maksym-letiushov** [comment]
@serejahh thank you. @artemSydorenko could you plz take a look ?

**Comment by Art3mS1d** [comment]
Now merged)

**Comment by alfredcc** [comment]
Thanks, all. I am very enjoy it; )
