### ISSUE TITLE
Content offset changes after pull at bottom in iOS 11

### ISSUE THREAD

**Issue by magic3584** [Yalantis/PullToRefresh#92]
### What happened instead?

TableView's contentOffset changes after pull at bottom

### Your Environment

- Version of the component: 3.0.1
- Swift version: 4.0
- iOS version: 11.1.2
- Device: 7
- Xcode version: 9.2

### Project that demonstrates the bug
[Bug demo](https://github.com/magic3584/testRefresh)

**Comment by sergey-prikhodko** [comment]
Hello @magic3584 , sorry for the late reply.
I reviewed this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue
